# Part of the Van Sales project.

from odoo import _, api, fields, models
from odoo.exceptions import UserError

DEVICE_SEQUENCE_CODE = 'van.sales.device'


class VanSalesDevice(models.Model):
    """A phone or tablet registered to a salesman.

    First-class, unlike Red Ladder where ``X-Device-ID`` is only a hint: the
    device carries the sync watermark and - more importantly - a **device
    number** issued once by the server, which lets it number its own receipts
    while offline without ever colliding with another device.

    That is the mechanism Odoo's own Point of Sale uses
    (``pos.config.register_new_device_identifier``): the number comes from a
    ``no_gap`` sequence, so two devices cannot receive the same one, and it is
    requested exactly once in the device's lifetime.
    """

    _name = 'van.sales.device'
    _description = "Van Sales Device"
    _order = 'last_seen_at desc, id desc'
    _check_company_auto = True

    name = fields.Char(
        string="Device", compute='_compute_name', store=True)
    device_uuid = fields.Char(
        string="Device ID", required=True, index=True, copy=False, readonly=True,
        help="Stable identifier generated by the handset. Sent on every call "
             "as the X-Device-ID header.")
    device_number = fields.Char(
        string="Device Number", readonly=True, copy=False, index=True,
        help="Issued once by the server. The app prefixes its offline "
             "document references with it, so two devices can never generate "
             "the same reference.")
    user_id = fields.Many2one(
        'res.users', string="Salesman", required=True, ondelete='cascade',
        index=True)
    van_id = fields.Many2one(
        'fleet.vehicle', string="Van", index='btree_not_null',
        check_company=True,
        help="Resolved from the salesman's van when the device registers.")
    company_id = fields.Many2one(
        'res.company', string="Company", required=True, index=True,
        default=lambda self: self.env.company)
    device_type = fields.Selection(
        selection=[('android', "Android"), ('ios', "iOS"), ('other', "Other")],
        default='android')
    device_model = fields.Char(string="Model")
    app_version = fields.Char(string="App Version")
    os_version = fields.Char(string="OS Version")
    fcm_token = fields.Char(string="FCM Token", index='btree_not_null')
    active = fields.Boolean(default=True,
        help="Untick to cut this device off. It stops being able to sync from "
             "its very next call.")
    registered_at = fields.Datetime(
        string="Registered", readonly=True, default=fields.Datetime.now)
    last_seen_at = fields.Datetime(string="Last Seen", readonly=True)
    last_sync_at = fields.Datetime(
        string="Last Sync Watermark", readonly=True,
        help="Server time of this device's last successful pull. The next "
             "pull returns only what changed after it.")
    push_count = fields.Integer(string="Records Pushed", readonly=True, default=0)
    sync_log_ids = fields.One2many(
        'van.sales.sync.log', 'device_id', string="Sync Log")
    sync_log_count = fields.Integer(compute='_compute_sync_log_count')

    _device_uuid_unique = models.Constraint(
        'UNIQUE(device_uuid)', "This device is already registered.")

    @api.depends('user_id', 'device_model', 'device_uuid')
    def _compute_name(self):
        for device in self:
            label = device.device_model or device.device_uuid or ''
            device.name = "%s / %s" % (
                device.user_id.name or '', label[:24]) if label else (
                    device.user_id.name or '')

    def _compute_sync_log_count(self):
        counts = {}
        if self.ids:
            for device, count in self.env['van.sales.sync.log']._read_group(
                    [('device_id', 'in', self.ids)], ['device_id'], ['__count']):
                counts[device.id] = count
        for device in self:
            device.sync_log_count = counts.get(device.id, 0)

    # ------------------------------------------------------------------
    # Registration
    # ------------------------------------------------------------------
    @api.model
    def _issue_device_number(self):
        """Next device number, from a no-gap sequence.

        ``no_gap`` on purpose: the number is half of every offline document
        reference the device will ever generate, so two devices receiving the
        same one would produce colliding references in the field.
        """
        sequence = self.env['ir.sequence'].sudo().search([
            ('code', '=', DEVICE_SEQUENCE_CODE),
        ], limit=1)
        if not sequence:
            raise UserError(_(
                "The Van Sales Device sequence is missing. Reinstall or "
                "upgrade Van Sales - Mobile API."))
        return sequence._next()

    @api.model
    def register(self, user, device_uuid, values=None):
        """Find or create the device for this handset. Idempotent.

        Re-registering an existing handset refreshes its details and re-binds
        it to the salesman's current van; it never issues a second device
        number, because the app's already-issued references depend on the
        first one.
        """
        values = dict(values or {})
        device = self.sudo().with_context(active_test=False).search([
            ('device_uuid', '=', device_uuid),
        ], limit=1)
        van = self.env['fleet.vehicle'].sudo().search([
            ('is_sales_van', '=', True),
            ('salesman_user_id', '=', user.id),
        ], limit=1)
        payload = {
            'user_id': user.id,
            'van_id': van.id or False,
            'company_id': (van.company_id or user.company_id or self.env.company).id,
            'last_seen_at': fields.Datetime.now(),
        }
        payload.update({
            key: values[key] for key in
            ('device_type', 'device_model', 'app_version', 'os_version', 'fcm_token')
            if values.get(key)
        })
        if device:
            device.sudo().write(payload)
            return device
        payload.update({
            'device_uuid': device_uuid,
            'device_number': self._issue_device_number(),
        })
        return self.sudo().create(payload)

    def touch(self, app_version=None):
        """Stamp last seen. Cheap enough to call on every authenticated call."""
        values = {'last_seen_at': fields.Datetime.now()}
        if app_version and app_version != self.app_version:
            values['app_version'] = app_version
        self.sudo().write(values)

    # ------------------------------------------------------------------
    # Admin actions
    # ------------------------------------------------------------------
    def action_deactivate(self):
        self.write({'active': False})
        self.env['van.sales.api.token'].sudo().search([
            ('device_uuid', 'in', self.mapped('device_uuid')),
            ('active', '=', True),
        ]).write({'active': False})
        return True

    def action_activate(self):
        self.write({'active': True})
        return True

    def action_reset_sync(self):
        """Force the next pull to be a full bootstrap."""
        self.write({'last_sync_at': False})
        return True

    def action_view_sync_log(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _("Sync Log"),
            'res_model': 'van.sales.sync.log',
            'view_mode': 'list,form',
            'domain': [('device_id', '=', self.id)],
        }
