# Part of the Van Sales project.

from odoo import _, api, fields, models

SYNC_STATUSES = [
    ('success', "Success"),
    ('duplicate', "Duplicate (ignored)"),
    ('rejected', "Rejected"),
    ('error', "Error"),
]


class VanSalesSyncLog(models.Model):
    """One row per record a device pushed. The idempotency ledger.

    A van loses signal constantly, so the app will re-send batches whose reply
    it never received. Without this ledger every retry would create a second
    order. The client UUID is unique here, so the second attempt is recognised
    and the original result replayed instead of acted on again.
    """

    _name = 'van.sales.sync.log'
    _description = "Van Sales Sync Log"
    _order = 'create_date desc, id desc'

    batch_uuid = fields.Char(string="Batch", index=True, readonly=True)
    client_uuid = fields.Char(
        string="Client Reference", required=True, index=True, readonly=True,
        help="Generated by the device before the record was ever sent. This is "
             "what makes a retry safe.")
    device_id = fields.Many2one(
        'van.sales.device', string="Device", ondelete='set null', index=True,
        readonly=True)
    user_id = fields.Many2one(
        'res.users', string="Salesman", ondelete='set null', index=True,
        readonly=True)
    res_model = fields.Char(string="Model", index=True, readonly=True)
    res_id = fields.Integer(string="Record ID", readonly=True)
    record_ref = fields.Char(string="Record", readonly=True)
    status = fields.Selection(
        selection=SYNC_STATUSES, string="Status", required=True,
        index=True, readonly=True)
    error_code = fields.Char(string="Error Code", index=True, readonly=True)
    error_message = fields.Text(readonly=True)
    payload = fields.Text(readonly=True)
    captured_at = fields.Datetime(
        string="Captured On Device", readonly=True,
        help="When the salesman actually did it, as opposed to when the "
             "server received it.")
    duration_ms = fields.Float(readonly=True)

    _client_uuid_unique = models.Constraint(
        'UNIQUE(client_uuid)',
        "This client reference has already been processed.")

    @api.model
    def find_processed(self, client_uuid):
        """Return an earlier successful entry for this UUID, if any."""
        if not client_uuid:
            return self.browse()
        return self.sudo().search([
            ('client_uuid', '=', client_uuid),
            ('status', 'in', ('success', 'duplicate')),
        ], limit=1)

    def action_open_record(self):
        self.ensure_one()
        if not (self.res_model and self.res_id):
            return False
        return {
            'type': 'ir.actions.act_window',
            'name': _("Record"),
            'res_model': self.res_model,
            'res_id': self.res_id,
            'view_mode': 'form',
        }
