# Part of the Van Sales project.

from odoo import fields, models


class VanSalesVisit(models.Model):
    """Visits gain a client reference so a re-sent check-in cannot duplicate."""

    _inherit = 'van.sales.visit'

    van_client_uuid = fields.Char(
        string="Client Reference", copy=False, index='btree_not_null',
        help="Generated by the device before the record was ever sent.")

    _van_client_uuid_uniq = models.Constraint(
        'UNIQUE(van_client_uuid)',
        "A visit with this client reference already exists.")
