# Part of the Van Sales project.

from odoo import fields, models


class AccountMove(models.Model):
    _inherit = 'account.move'

    van_id = fields.Many2one(
        comodel_name='fleet.vehicle', string="Van",
        domain="[('is_sales_van', '=', True)]",
        check_company=True, index='btree_not_null', copy=False)
    van_route_id = fields.Many2one(
        comodel_name='van.sales.route', string="Route",
        index='btree_not_null', check_company=True, copy=False)
    van_visit_id = fields.Many2one(
        comodel_name='van.sales.visit', string="Visit",
        index='btree_not_null', check_company=True, copy=False)
    van_salesman_user_id = fields.Many2one(
        comodel_name='res.users', string="Van Salesman",
        related='van_id.salesman_user_id', store=True,
        index='btree_not_null')
    van_client_uuid = fields.Char(
        string="Client Reference", copy=False, index='btree_not_null',
        help="Identifier generated by the mobile device, so a re-sent invoice "
             "cannot be duplicated.")
    van_captured_datetime = fields.Datetime(
        string="Captured On", copy=False,
        help="When the salesman raised it, as opposed to when the server "
             "received it.")

    _van_client_uuid_uniq = models.Constraint(
        'UNIQUE(van_client_uuid)',
        "An invoice with this client reference already exists.",
    )
