# Part of the Van Sales project.

from collections import defaultdict

from odoo import _, api, fields, models
from odoo.exceptions import UserError


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    van_id = fields.Many2one(
        comodel_name='fleet.vehicle', string="Van",
        domain="[('is_sales_van', '=', True)]",
        check_company=True, index='btree_not_null', tracking=True,
        help="Selling this order out of a van ships it from the van's own "
             "stock instead of the warehouse.")
    van_route_id = fields.Many2one(
        comodel_name='van.sales.route', string="Route",
        index='btree_not_null', check_company=True)
    van_visit_id = fields.Many2one(
        comodel_name='van.sales.visit', string="Visit",
        index='btree_not_null', check_company=True,
        help="The customer stop this order was taken at.")
    van_salesman_user_id = fields.Many2one(
        comodel_name='res.users', string="Van Salesman",
        related='van_id.salesman_user_id', store=True,
        index='btree_not_null')
    van_delivery_route_id = fields.Many2one(
        comodel_name='stock.route', string="Van Delivery Route",
        related='van_id.van_delivery_route_id', readonly=True,
        help="Route that makes the delivery leave the van's stock location.")
    van_client_uuid = fields.Char(
        string="Client Reference", copy=False, index='btree_not_null',
        help="Identifier generated by the mobile device. Makes a re-sent "
             "order impossible to duplicate.")
    van_captured_datetime = fields.Datetime(
        string="Captured On", copy=False,
        help="When the salesman actually took the order, which is not the same "
             "as when the server received it.")
    van_credit_warning = fields.Char(
        string="Credit Warning", copy=False, readonly=True,
        help="Recorded when the order was confirmed past the customer's credit "
             "limit under a Warn policy.")

    _van_client_uuid_uniq = models.Constraint(
        'UNIQUE(van_client_uuid)',
        "An order with this client reference already exists.",
    )

    # --------------------------------------------------------------------
    # Van checks, applied at confirmation
    # --------------------------------------------------------------------
    def _van_sales_required_quantities(self):
        """Quantity needed per product, in the product's own unit.

        Summed across lines on purpose: three lines of six each must fail
        against a van carrying ten, even though no single line does.
        """
        self.ensure_one()
        needed = defaultdict(float)
        for line in self.order_line:
            product = line.product_id
            if not product or not product.is_storable or line.display_type:
                continue
            uom = line.product_uom_id
            quantity = line.product_uom_qty
            if uom and uom != product.uom_id:
                quantity = uom._compute_quantity(
                    quantity, product.uom_id, round=False)
            needed[product] += quantity
        return needed

    def _van_sales_check_stock(self):
        """Apply the over-sell policy configured in Van Sales - Stock."""
        self.ensure_one()
        van = self.van_id
        if not van or not van.van_location_id:
            return
        blocked, warned = [], []
        available = van._van_sales_available_quantities()
        for product, needed in self._van_sales_required_quantities().items():
            on_van = available.get(product.id, 0.0)
            if product.uom_id.compare(needed, on_van) <= 0:
                continue
            policy = product.van_sale_stock_policy_effective or 'warn'
            message = _(
                "%(product)s: %(needed).2f needed, %(available).2f on the van",
                product=product.display_name, needed=needed, available=on_van)
            if policy == 'block':
                blocked.append(message)
            elif policy == 'warn':
                warned.append(message)
        if blocked:
            raise UserError(_(
                "Van %(van)s is not carrying enough stock for this order:\n\n"
                "%(details)s\n\n"
                "These products are set to block over-selling. Load the van, "
                "reduce the quantities, or change the product's van over-sell "
                "policy.",
                van=van.display_name, details="\n".join(blocked)))
        if warned:
            # A backend action cannot raise a non-blocking dialog, so the
            # warning is recorded where it stays visible instead of flashing
            # past. The mobile app will show it as a prompt.
            self.message_post(body=_(
                "Confirmed with more than the van is carrying:<br/>%s",
                "<br/>".join(warned)))

    def _van_sales_check_credit(self):
        """Apply the company's credit policy.

        Odoo only ever warns about a credit limit - ``_build_credit_warning_message``
        returns a string that views render as a banner, and there is no hard
        block anywhere in the product. This turns it into one when the business
        wants it.
        """
        self.ensure_one()
        company = self.company_id or self.env.company
        policy = company.van_sale_credit_policy or 'warn'
        if policy == 'allow' or not company.account_use_credit_limit:
            return
        rate = self.currency_rate or 1.0
        warning = self.env['account.move']._build_credit_warning_message(
            self.sudo(), current_amount=(self.amount_total / rate))
        if not warning:
            return
        if policy == 'block':
            raise UserError(_(
                "%(warning)s\n\nThis company blocks van orders that go past a "
                "customer's credit limit. Collect against the outstanding "
                "invoices first, or ask the office to raise the limit.",
                warning=warning))
        self.van_credit_warning = warning
        self.message_post(body=_("Confirmed past the credit limit: %s", warning))

    def action_confirm(self):
        for order in self.filtered('van_id'):
            order._van_sales_check_stock()
            order._van_sales_check_credit()
        return super().action_confirm()

    # --------------------------------------------------------------------
    # Carrying the van context onto the invoice
    # --------------------------------------------------------------------
    def _prepare_invoice(self):
        values = super()._prepare_invoice()
        if self.van_id:
            values.update({
                'van_id': self.van_id.id,
                'van_route_id': self.van_route_id.id,
                'van_visit_id': self.van_visit_id.id,
            })
        return values

    # --------------------------------------------------------------------
    # Actions
    # --------------------------------------------------------------------
    def action_van_sales_view_visit(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _("Visit"),
            'res_model': 'van.sales.visit',
            'view_mode': 'form',
            'res_id': self.van_visit_id.id,
        }


class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    def _prepare_procurement_values(self):
        """Steer the delivery to the van's route.

        ``route_ids`` in the procurement values is the officially supported
        lever: ``stock.rule._get_rule`` gives those routes top priority when
        choosing a rule, and the chosen rule's ``location_src_id`` becomes the
        move's source. Nothing here overrides core behaviour - it just tells
        procurement which route to prefer.
        """
        values = super()._prepare_procurement_values()
        route = self.order_id.van_id.van_delivery_route_id
        if route:
            existing = values.get('route_ids') or self.env['stock.route']
            values['route_ids'] = route | existing
        return values
